[[Xorg_libXdmcp]]
arch = "armv7l"
git-tree-sha1 = "1c7c8dfdd17987d6f01d442f29b63846d986bb7b"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "76fad7fc99cefc833dcd4bbf9b8e9cb3f941c454fba8320ef74eb8899c9f6fa8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXdmcp]]
arch = "i686"
git-tree-sha1 = "7b3908ba7d3445386ff6d848808e49cd71fa4631"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "3801a56aaccdd8eaaac665010ae1b601771e84834af40212b0fdfbeac7e4abf7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.i686-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "aarch64"
git-tree-sha1 = "6edbd8e099a38527668af6ed7f5b3fb7e06bd814"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "77cda920e3a57143d48eda2508aac2773b4f062fa68dbdb4e20528a383e7141d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.aarch64-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "armv7l"
git-tree-sha1 = "0c6becf5e93fe28518ac8d2a2a9ae94f4c3be689"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "e4e7df467eedd693ea0dbc191c95239dc7a6553fb8c75c1cefb33806eabaee9f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXdmcp]]
arch = "aarch64"
git-tree-sha1 = "0c25ede0bae2d966315dbf38e4d985b41d1da62a"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "c1dbcfa71121597e79f1578b9de707f0ee57e818290887cb7a307cc18979ceec"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.aarch64-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "95eaf787d74d614e12c5af8fb9c9540de26bf63c"
os = "freebsd"

    [[Xorg_libXdmcp.download]]
    sha256 = "cf1e72868052ce6e76531bc4d38af684f3c165032a4a9ded78b57d4fc5e773af"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXdmcp]]
arch = "i686"
git-tree-sha1 = "5fce7069706e9b7534c9e7b3d7c5f383af137d75"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "14a14e5576509c58c8fe781b154f845a380442cc691299a7f5696426cace316d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.i686-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "44ffed3d3eb15fddc855067c088bb5536b914aeb"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "5391c89aab1a46f2fc96722ebdb7e4986a7e19f84d76a59e1a797769c8ad18a6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.x86_64-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "99a036f584ecd22c61d8a4e69f1b829bc9270460"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "70e2da4f24b6891dabfb94555ac612d496f881a313aaa51545d4f8fbe2721971"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.x86_64-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "powerpc64le"
git-tree-sha1 = "193016ea0fe5bddc0f257d5b81d7ed9026828d72"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "93a13e24f26c2acb96c5856f8b48060f989e625dd8bce9cd81f40d56dcb07d1a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+2/Xorg_libXdmcp.v1.1.3.powerpc64le-linux-gnu.tar.gz"
