[[Xorg_libXdmcp]]
arch = "aarch64"
git-tree-sha1 = "ee21315f5cd469486dd7bb2ccf4dde1ee3416244"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "ff382977920b783b268898e75d631e8d5ea142556ee3d7b226b5e64af8dba4a9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.aarch64-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "aarch64"
git-tree-sha1 = "078c6e2dab1df4a3d0a20f604d352d36f7006573"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "9ac70d4bf2b99afdbe4ec1a2cf7d63d60e8cd8385379ac7ec963d7c9b8ef5cf6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.aarch64-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "7c2add28f53188146dc28d22b77320949580fe94"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "2dadb0cf0ff061725427573332f52d4c4f73bff513a20c555a26eba5a8ca49f5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.x86_64-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "powerpc64le"
git-tree-sha1 = "44bef3c1b54093e9d9b3d13eea9e7ed523d4f6ae"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "ad59ccaf387119f9a05a4395b1546138cd24c3567f7c7828cbe1ab0b842dfd86"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "ec81d6c8186ffdbd17846d1e33ff29ae850a4d28"
os = "freebsd"

    [[Xorg_libXdmcp.download]]
    sha256 = "c868a5425973af353b9ab89d58c06a060df7b6c4b42ad0630d4ae44118d2bafb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXdmcp]]
arch = "i686"
git-tree-sha1 = "2480275fbaf0043a7c1401354476edb548045028"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "25dda894e3fef67ef1ee6953735ab082de039816a21a27c1327cf74aec6ff880"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.i686-linux-gnu.tar.gz"
[[Xorg_libXdmcp]]
arch = "i686"
git-tree-sha1 = "d394b4884f53d747b7facb22dd13e88010f781ce"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "062c91f200d00e09187e982e7017e37785f170cd79ea7df512e1b61a56c306e1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.i686-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "armv7l"
git-tree-sha1 = "0dac8f4c660e5d148ed59b7659c7f2352643f0cc"
libc = "glibc"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "a287ea3c4630b0afd24e530f32cc97117e81848a8ef00a35cf85648117e437b0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXdmcp]]
arch = "x86_64"
git-tree-sha1 = "5e45060bd897fec00c0897444e097f2c5fbd3248"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "6459f517861929f4f7abfafb63d41f6e4262068abe77b250ca5ae846304370bb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.x86_64-linux-musl.tar.gz"
[[Xorg_libXdmcp]]
arch = "armv7l"
git-tree-sha1 = "dbfbb0547cfb75242936f9bddf55aa7e6abd0a30"
libc = "musl"
os = "linux"

    [[Xorg_libXdmcp.download]]
    sha256 = "7e37d7c24980c23a70567e75cc9421ba96bf1dde5e9a315f32845e434dc0a755"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+1/Xorg_libXdmcp.v1.1.3.armv7l-linux-musleabihf.tar.gz"
